server:
  port: 8084

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: bridge-challenge
          uri: lb://bridge-challenge
          predicates:
            - Path=/catalog/**
          filters:
            - name: CircuitBreaker
              args:
                name: bridge-challenge
                fallbackuri: forward:/itemFallBack
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://challenge-server:8761/eureka
  instance:
    hostname: cloud-gateway

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /
      path-mapping:
        health: health
        
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  